<!doctype html>
<html lang="en">
<style>
    table, tr, td {
        border: 1px solid black;
    }

    .isInvisible {
        display: none;
    }
</style>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Agenda</title>
</head>
<body>

<form method="POST">
    <input type="radio" id="dag" name="form" value="dag">
    <label for="dag">dag</label>
    <input type="radio" id="week" name="form" value="week">
    <label for="week">week</label>
    <input type="radio" id="maand" name="form" value="maand">
    <label for="maand">maand</label>

</form>

<p id="output"></p>

<table id="maandTable">
    <tr>
        <td>Maandag</td>
        <td>Dinsdag</td>
        <td>Woensdag</td>
        <td>Donderdag</td>
        <td>Vrijdag</td>
        <td>Zaterdag</td>
        <td>Zondag</td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
</table>
<table id="dagTable">
    <tr>
        <td>datum</td>
    </tr>
    <tr>
        <td>0</td>
        <td></td>
    </tr>
    <tr>
        <td>1</td>
        <td></td>
    </tr>
    <tr>
        <td>2</td>
        <td></td>
    </tr>
    <tr>
        <td>3</td>
        <td></td>
    </tr>
    <tr>
        <td>4</td>
        <td></td>
    </tr>
    <tr>
        <td>5</td>
        <td></td>
    </tr>
    <tr>
        <td>6</td>
        <td></td>
    </tr>
    <tr>
        <td>7</td>
        <td></td>
    </tr>
    <tr>
        <td>8</td>
        <td></td>
    </tr>
    <tr>
        <td>9</td>
        <td></td>
    </tr>
    <tr>
        <td>10</td>
        <td></td>
    </tr>
    <tr>
        <td>11</td>
        <td></td>
    </tr>
    <tr>
        <td>12</td>
        <td></td>
    </tr>
    <tr>
        <td>13</td>
        <td></td>
    </tr>
    <tr>
        <td>14</td>
        <td></td>
    </tr>
    <tr>
        <td>15</td>
        <td></td>
    </tr>
    <tr>
        <td>16</td>
        <td></td>
    </tr>
    <tr>
        <td>17</td>
        <td></td>
    </tr>
    <tr>
        <td>18</td>
        <td></td>
    </tr>
    <tr>
        <td>19</td>
        <td></td>
    </tr>
    <tr>
        <td>20</td>
        <td></td>
    </tr>
    <tr>
        <td>21</td>
        <td></td>
    </tr>
    <tr>
        <td>22</td>
        <td></td>
    </tr>
    <tr>
        <td>23</td>
        <td></td>
    </tr>

</table>
<table id="weekTable">
    <tr>
        <td></td>
        <td>Maandag</td>
        <td>Dinsdag</td>
        <td>Woensdag</td>
        <td>Donderdag</td>
        <td>Vrijdag</td>
        <td>Zaterdag</td>
        <td>Zondag</td>
    </tr>
    <tr>
        <td>0</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>1</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>2</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>3</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>4</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>5</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>6</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>7</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>8</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>9</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>10</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>11</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>12</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>13</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>14</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>15</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>16</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>17</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>18</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>19</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>20</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>21</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>22</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>23</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
</table>
</body>
</html>

<script>
    const radioButtons = document.querySelectorAll('input[name="form"]');
    for (const radioButton of radioButtons) {
        radioButton.addEventListener('change', showSelected);
    }

    function showSelected(e) {
        if (this.value === 'dag') {
            document.getElementById('dagTable').classList.remove('isInvisible');
            document.getElementById('weekTable').classList.add('isInvisible');
            document.getElementById('maandTable').classList.add('isInvisible');
            console.log(document.getElementById('weekTable').classList)
        } else if (this.value === 'week') {
            document.getElementById('dagTable').classList.add('isInvisible');
            document.getElementById('weekTable').classList.remove('isInvisible');
            document.getElementById('maandTable').classList.add('isInvisible');
        } else if (this.value === 'maand') {
            document.getElementById('dagTable').classList.add('isInvisible');
            document.getElementById('weekTable').classList.add('isInvisible');
            document.getElementById('maandTable').classList.remove('isInvisible');
        }
    }
</script>